# Iusmorfos Configuration: Reproducible Settings
# All random seeds and parameters for exact replication

# === REPRODUCIBILITY SETTINGS ===
reproducibility:
  random_seed: 42  # Master seed for all random operations
  numpy_seed: 42
  python_seed: 42
  hash_seed: 42  # For dictionary ordering consistency

# === EXPERIMENT PARAMETERS ===
experiment:
  generations: 30  # Default number of generations
  offspring_per_generation: 9  # Following Dawkins original
  mutation_rate: 1  # ±1 per dimension per generation
  
  # Fitness function weights (must sum to 1.0)
  fitness_weights:
    complexity: 0.4
    diversity: 0.3
    balance: 0.3
  
  # Initial jusmorph (9D vector)
  initial_jusmorph: [1, 1, 1, 1, 1, 1, 1, 1, 1]  # "Neminem Laedere"

# === IUSPACE DIMENSIONS ===
iuspace:
  dimensions: 9
  ranges:
    formalism: [1, 10]
    centralization: [1, 10]
    codification: [1, 10]
    individualism: [1, 10]
    punitiveness: [1, 10]
    procedural_complexity: [1, 10]
    economic_integration: [1, 10]
    internationalization: [1, 10]
    digitalization: [1, 10]

# === DATA PATHS ===
paths:
  data_dir: "data"
  results_dir: "results"
  outputs_dir: "outputs"
  logs_dir: "logs"
  
  # Input files
  innovations_file: "data/innovations_exported.csv"
  evolution_cases: "data/evolution_cases.csv"
  velocity_metrics: "data/velocity_metrics.csv"
  
  # Output files
  experiment_results: "results/experiment_results_{timestamp}.json"
  validation_results: "results/validation_results_{timestamp}.json"
  evolution_plots: "outputs/evolution_plots_{timestamp}.png"

# === VALIDATION SETTINGS ===
validation:
  # Regression test tolerances
  tolerances:
    overall_score: 0.05  # ±5%
    gamma_estimate: 0.2  # ±0.2
    complexity_growth: 0.1  # ±10%
    fitness_convergence: 3  # ±3 generations
  
  # Bootstrap analysis
  bootstrap:
    n_samples: 1000
    confidence_level: 0.95
    method: "percentile"
  
  # Empirical validation thresholds
  empirical_thresholds:
    min_accuracy: 0.70  # Minimum acceptable accuracy
    min_correlation: 0.50  # Minimum correlation with real data
    min_sample_size: 25  # Minimum validation dataset size

# === STATISTICAL MODELS ===
models:
  # Power-law analysis
  power_law:
    fit_method: "KS"  # Kolmogorov-Smirnov
    min_data_points: 50
    
  # Baseline comparisons
  baselines:
    - name: "dummy_classifier"
      strategy: "most_frequent"
    - name: "logistic_regression" 
      solver: "lbfgs"
      max_iter: 1000
    - name: "random_forest"
      n_estimators: 100
      random_state: 42

# === VISUALIZATION SETTINGS ===
visualization:
  figure_size: [12, 8]
  dpi: 300
  format: "png"
  style: "seaborn-v0_8"
  color_palette: "husl"
  
  # Plot types to generate
  plots:
    evolution_trajectory: true
    fitness_convergence: true
    dimensional_analysis: true
    legal_family_emergence: true
    validation_diagnostics: true

# === LOGGING CONFIGURATION ===
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_file: "logs/iusmorfos_{timestamp}.log"
  
# === CI/CD SETTINGS ===
ci:
  python_versions: ["3.8", "3.9", "3.10"]
  test_timeout: 600  # 10 minutes
  coverage_threshold: 0.80  # 80% minimum coverage